import Head from 'next/head'
import { Inter } from '@next/font/google'
import Alarm from '../components/Alarm/index';
import useTranslation from 'next-translate/useTranslation';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const { t } = useTranslation();

  return (
    <>
      <Head>
        <title>Clock App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Rubik&display=swap" rel="stylesheet" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Orbitron&display=swap" rel="stylesheet" />
      </Head>
      <Alarm />
    </>
  )
}
