import Head from 'next/head'
import Alarm from '../components/Alarm/index';
import axios from "axios";
import {GET_COUNTRY_API, GET_TIMEZONE_BY_COUNTRY} from "../constant/endpoints";

const Home = ({ countryData, timezoneData }) => {

  return (
    <>
      <Head>
        <title>Clock App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link href="https://fonts.googleapis.com/css2?family=Rubik&display=swap" rel="stylesheet" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link href="https://fonts.googleapis.com/css2?family=Orbitron&display=swap" rel="stylesheet" />
      </Head>
      <Alarm countryData={countryData} timezoneData={timezoneData} />
    </>
  )
};

export async function getServerSideProps () {

  let countryData, timezoneData;

  await axios.get(GET_COUNTRY_API)
      .then((response) => {
        countryData = response.data;
      })
      .catch((error) => {
        console.log(error);
      });

    await axios.get(GET_TIMEZONE_BY_COUNTRY)
        .then((response) => {
            timezoneData = response.data;
        })
        .catch((error) => {
            console.log(error);
        });

  return {
    props: {
        countryData,
        timezoneData
    }
  }
}

export default Home;
