import Head from 'next/head';
import React, {useEffect} from 'react';
import styles from '../styles/Reminder.module.css';
import ReminderCom from '../components/Reminder/index';
import axios from "axios";
import {GET_CATEGORIES, GET_COUNTRY_API, GET_TIMEZONE_BY_COUNTRY} from "../constant/endpoints";

const Reminder = ({ categoryData }) => {

    return (
        <>
            <Head>
                <title>Clock App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
                <link href="https://fonts.googleapis.com/css2?family=Rubik&display=swap" rel="stylesheet" />
            </Head>
            <div className={styles.main}>
                <ReminderCom categoryData={categoryData} />
            </div>
        </>
    )
};

export async function getServerSideProps () {

    let categoryData;

    await axios.get(GET_CATEGORIES)
        .then((response) => {
            categoryData = response.data;
        })
        .catch((error) => {
            console.log(error);
        });

    return {
        props: {
            categoryData
        }
    }
}

export default Reminder;