import Head from 'next/head';
import React, {useEffect} from 'react';
import Footer from '../components/Footer';
import Header from '../components/Header';
import styles from '../styles/Index.module.css';
import moment from "moment-timezone";

const Reminder = () => {

    useEffect(() => {
        const date = new Date();
        console.log(date.toLocaleString('en-US', { timeZone: "America/Los_Angeles" }));
    }, []);

    return (
        <>
            <Head>
                <title>Clock App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
                <link href="https://fonts.googleapis.com/css2?family=Rubik&display=swap" rel="stylesheet" />
            </Head>
            
        </>
    )
}

export default Reminder;