import Head from 'next/head';
import React from 'react';
import Clock from '../components/Clock';
import styles from "../styles/Time.module.css";

const Time = () => {

    return (
        <>
            <Head>
                <title>Clock App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
                <link href="https://fonts.googleapis.com/css2?family=Rubik&display=swap" rel="stylesheet" />
            </Head>
            <div className={styles.main}>
                <Clock />
            </div>
        </>
    )
}

export default Time;